[package]
name = "vegafusion-wasm"
version = "0.8.0"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib",]

[features]
default = [ "console_error_panic_hook",]

[dependencies]
serde_json = "1.0.81"
wasm-bindgen-futures = "0.4.28"
js-sys = "0.3.55"
prost = "0.10.3"
prost-types = "0.10.1"
indexmap = "1.9.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[dependencies.vegafusion-core]
path = "../vegafusion-core"

[dependencies.serde]
version = "1.0.137"
features = [ "derive",]

[dependencies.wasm-bindgen]
version = "0.2.78"

[dependencies.getrandom]
version = "0.2.3"
features = [ "js",]

[dependencies.chrono]
version = "0.4.19"
features = [ "wasmbind",]

[dependencies.console_error_panic_hook]
version = "0.1.6"
optional = true

[dependencies.wee_alloc]
version = "0.4.5"

[dependencies.web-sys]
version = "0.3.55"
features = [ "Document", "Element", "HtmlElement", "Node", "Window",]

[package.metadata.wasm-pack.profile.release]
wasm-opt = [ "-Os",]

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false
