[package]
name = "vegafusion-core"
license = "AGPL-3.0-or-later"
edition = "2021"
version = "0.8.0"

[features]
tonic_support = [ "tonic", "tonic-build",]
pyarrow = [ "pyo3", "arrow/pyarrow", "datafusion-common/pyarrow",]

[dependencies]
thiserror = "^1.0.29"
bytes = "1.1.0"
prost = "0.10.3"
prost-types = "0.10.1"
itertools = "0.10.3"
lazy_static = "^1.4.0"
regex = "^1.5.5"
serde_json = "1.0.81"
ordered-float = "^2.10.0"
petgraph = "0.6.0"
deterministic-hash = "1.0.1"
chrono = "0.4.19"

[dependencies.arrow]
version = "19.0.0"
default_features = false
features = [ "ipc",]

[dependencies.datafusion-common]
git = "https://github.com/apache/arrow-datafusion.git"
rev = "176f4329dad5800c2f0c29edd21086f899bef676"

[dependencies.pyo3]
version = "0.16.4"
optional = true

[dependencies.serde]
version = "1.0.137"
features = [ "derive",]

[dependencies.tonic]
version = "0.7.2"
optional = true

[build-dependencies.prost-build]
version = "0.10.3"

[build-dependencies.tonic-build]
version = "0.7.2"
optional = true
